package com.example.IronLibrary.tests;

import com.example.IronLibrary.model.Author;
import com.example.IronLibrary.model.Book;
import org.testng.annotations.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class AuthorTest {

    @Test
    public void testGetAuthorData() {
        Book testBook = new Book("A7", "Harry Potter", "Ficcion", 4);
        Author testAuthor = new Author("J.K. Rowling", "jkrowling@example.com", testBook);

        Integer expectedAuthorId = null; // since the authorId is generated by the database, we don't know its value until it's saved
        assertEquals(expectedAuthorId, testAuthor.getAuthorId());

        String expectedAuthorName = "J.K. Rowling";
        assertEquals(expectedAuthorName, testAuthor.getName());

        String expectedEmail = "jkrowling@example.com";
        assertEquals(expectedEmail, testAuthor.getEmail());

        Book expectedBook = testBook;
        assertEquals(expectedBook, testAuthor.getAuthorBook());
    }

}
