package com.example.IronLibrary.tests;

import com.example.IronLibrary.model.Book;
import com.example.IronLibrary.model.Issue;
import com.example.IronLibrary.model.Student;
import org.testng.annotations.Test;

import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class IssueTest {

    @Test
    public void testGetIssueData() {
        Student testStudent = new Student("123456789", "Martin");
        Book testBook = new Book("A7", "Harry Potter", "Ficcion", 4);
        Issue testIssue = new Issue(new Date(), new Date(), testStudent, testBook);

        Integer expectedIssueId = null; // since the issueId is generated by the database, we don't know its value until it's saved
        assertEquals(expectedIssueId, testIssue.getIssueID());

        Date expectedIssueDate = new Date();
        assertEquals(expectedIssueDate, testIssue.getIssueDate());

        Date expectedReturnDate = new Date();
        assertEquals(expectedReturnDate, testIssue.getReturnDate());

        Student expectedStudent = testStudent;
        assertEquals(expectedStudent, testIssue.getIssueStudent());

        Book expectedBook = testBook;
        assertEquals(expectedBook, testIssue.getIssueBook());
    }

}
